# tenant: ACME-PROD

tenant:
  name: ACME-PROD
  description: ACME Corporation - Production workloads
  annotation: orchestrated-by:aci-gitops-pipeline

  vrfs:
    - name: PROD-VRF
      description: Production VRF
      enforcement: enforced
      preferred_group: disabled

  bridge_domains:
    - name: WEB-BD
      vrf: PROD-VRF
      gateway: 10.10.10.1
      mask: '24'
      unicast_routing: true
      arp_flooding: false
      l2_unknown_unicast: proxy

    - name: APP-BD
      vrf: PROD-VRF
      gateway: 10.10.20.1
      mask: '24'
      unicast_routing: true
      arp_flooding: false
      l2_unknown_unicast: proxy

    - name: DB-BD
      vrf: PROD-VRF
      gateway: 10.10.30.1
      mask: '24'
      unicast_routing: true
      arp_flooding: false
      l2_unknown_unicast: proxy

  app_profiles:
    - name: ACME-3TIER
      epgs:
        - name: WEB-EPG
          bd: WEB-BD
          preferred_group: false
          contracts:
            provided: [EXT-TO-WEB]
            consumed: [WEB-TO-APP]
        - name: APP-EPG
          bd: APP-BD
          preferred_group: false
          contracts:
            provided: [WEB-TO-APP]
            consumed: [APP-TO-DB]
        - name: DB-EPG
          bd: DB-BD
          preferred_group: false
          contracts:
            provided: [APP-TO-DB]
            consumed: []

  contracts:
    - name: EXT-TO-WEB
      scope: tenant
      subjects:
        - name: HTTPS-SUBJ
          filters: [HTTPS-FILTER]
    - name: WEB-TO-APP
      scope: tenant
      subjects:
        - name: APP-SUBJ
          filters: [APP-8080-FILTER]
    - name: APP-TO-DB
      scope: tenant
      subjects:
        - name: DB-SUBJ
          filters: [MYSQL-FILTER]

  filters:
    - name: HTTPS-FILTER
      entries:
        - name: TCP-443
          ethertype: ip
          ip_protocol: tcp
          dest_from_port: '443'
          dest_to_port: '443'
    - name: APP-8080-FILTER
      entries:
        - name: TCP-8080
          ethertype: ip
          ip_protocol: tcp
          dest_from_port: '8080'
          dest_to_port: '8080'
    - name: MYSQL-FILTER
      entries:
        - name: TCP-3306
          ethertype: ip
          ip_protocol: tcp
          dest_from_port: '3306'
          dest_to_port: '3306'